# Generated by Django 5.0.7 on 2024-09-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='day',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='state',
        ),
    ]
