# Generated by Django 5.0.7 on 2024-09-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_setting', '0002_remove_companyinfo_city_remove_companyinfo_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
