# Generated by Django 5.0.7 on 2024-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='https://t4.ftcdn.net/jpg/04/73/25/49/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg', null=True, upload_to='home/choose/')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default='https://t4.ftcdn.net/jpg/04/73/25/49/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg', null=True, upload_to='home/choose/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the main title for the slider.', max_length=255, verbose_name='Title')),
                ('sub_title', models.CharField(help_text='Enter the subtitle for the slider.', max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(default='https://t4.ftcdn.net/jpg/04/73/25/49/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg', help_text='Upload an image for the slider. Default image will be used if none is provided.', upload_to='home/sliders/', verbose_name='Slider Image')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='Active', help_text='Status of the Slider', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
