# Generated by Django 5.0.7 on 2024-09-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
    ]
